//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winforms_Veronica_Alvarez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int AlumnoId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string Nombre { get; set; }
        public string DNI { get; set; }
        public string Telefono { get; set; }
        public string Estudios { get; set; }
        public Nullable<System.DateTime> ComienzoPracticas { get; set; }
        public bool SuperaPracticas { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
