//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT2E9_Veronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int PeliculaId { get; set; }
        public string Titulo { get; set; }
        public int Anno { get; set; }
        public string Genero { get; set; }
    }
}
