//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCine_Veronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyeccion
    {
        public int PeliculaId { get; set; }
        public int SesionId { get; set; }
        public System.DateTime Inicio { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
    
        public virtual Pelicula Peliculas { get; set; }
        public virtual Sesion Sesiones { get; set; }
    }
}
